### ISSUE TITLE
Address portability issue around FSST encoding support

### ISSUE THREAD

**Issue by springmeyer** [maplibre/maplibre-tile-spec#150]
## Context

Currently [FSST encoding](https://github.com/cwida/fsst) is used in this project.

The FSST implementation we depend on in the java code is a JNI module (which compiles a C++ module and loads it at runtime): https://github.com/maplibre/maplibre-tile-spec/tree/main/java/resources.

Up until very recently were having to manually compile and link locally which was brittle. So this was recently improved to run automatically as part of the java compile: #62 

## Problem

Limitations remain:

  - While theres is working and tested support for macOS (x86 and arm64), linux amd64, and windows x86_64, there are likely other platforms and architectures that are not supported (where the compile or linking may be broken)
  - The loading of the `FsstWrapper.so` is currently relative to the working directory. This means that the CLI tools and the java unit + benchmarks only work if run from within the `java` directory

So this needs to be improved. 

## Ideas for solutions

Potential solutions to consider:
 - Moving to a pure Java FSST implementation
 - Changing the `FsstWrapper.so` loading logic to be relative to the java file that loads it (or making other packaging fixes to make it portable)
 - Your idea here?

**Comment by msbarry** [comment]
+1 to a pure Java implementation, that would be easiest for projects like planetiler that will depend on this. But if you do end up with a native dependency, the xerial repos seem to be good examples of doing it well:

- https://github.com/xerial/sqlite-jdbc
- https://github.com/xerial/snappy-java

**Comment by msbarry** [comment]
I'm going to do a Java fsst encoder port if that sounds ok to you @springmeyer?

**Comment by springmeyer** [comment]
@msbarry great to hear you are interested. From my perspective what this project ideally needs is a robust, well-tested and maintained third party dependency to depend on. Short of that, the JNI bindings to the official C++ project feel like an okay compromise. If you feel up for helping push for something maintained that we can depend on here, I noticed some discussion to hook into at https://github.com/cwida/fsst/issues/14.
