### ISSUE TITLE
Rework dir structure

### ISSUE THREAD

**Issue by nyurik** [maplibre/maplibre-tile-spec#45]
The repo has become a bit disorganized, and could use a clearer structure. Here are some ideas, but since I don't know all the components of the system yet, its a rough draft that will keep improving until we can start moving dirs around and close this ticket.

I propose we organize by implementation languages plus additional dirs for the specification, shared test files, and shared utilities. Some of the dir names could be improved too.

* `/spec` - "official" documentation describing MLT specification.
  * `/v0` - since we do not have the first version yet, all work will be in `v0` until ready.  Once stable, we will rename this dir to `v1` and won't change it significantly thereafter.
* `/docs` - this is different than `/spec` - it will contain explanations, suggested implementations, performance benchmark results, and anything else useful to the reader.  Some README content will be moved here too.  I propose we use [mdbook format](https://rust-lang.github.io/mdBook/) (already used in Martin and other projects)
* `/test` - anything test-related that is not specific to an individual implementation language
  * `/fixtures/(omt|bing|...) - sample tiles from various sources, with their own licenses. This will be used for validation and performance benchmarks.
  * `/expected/(omt|bing|...)` - if converting MVT to MLT will always produce the same result, we should store that result here - so that every implementation can be validated against it.
* `/java` - JVM-focused implementation (can use java/kotlin/...). Published to Maven?
* `/js` - code for [NPM](https://npmjs.com), probably under `@maplibre/...` name, probably written in TypeScript
* `/rust` - Rust implementation, published [Crates](https://crates.io/), most likely will have bindings for C, C++, Python, and others
* `<more ideas here>`

**Comment by mactrem** [comment]
I like the proposed structure. It's similar to that what i had in mind of how we can structure the repo and also similiar to the structure of [Apache Arrow](https://github.com/apache/arrow). I would go with `js` for the JavaScript decoder

**Comment by springmeyer** [comment]
I also like the overall proposed structure 👍🏼 How about we aim to get CI green with the existing structure (ideally this week) and then with that foundation in place we could re-organize the repo soon after while ensuring all tests keep passing (of course the gh actions workflow will need updated too)?

**Comment by nyurik** [comment]
sounds perfect, thx!  Let me know if you need any help

**Comment by nyurik** [comment]
One related proposal:  I think it would be best to use [just](https://github.com/casey/just) for all orchestration - a user friendly variant of `make` with similar syntax. We have used in in Martin and numerous other projects.

Basically, all build, test, bless, and other useful commands could be done as small Just recipes -- cross-platform and cross-language. CI could then rely on these - which means all testing in CI and locally would be done with the same code (there is usually a lot of problems running CI tasks locally if their code is mostly in the GitHub workflow).

Installing in a workflow:

```yaml
- uses: taiki-e/install-action@v2
  with: { tool: just }
```

Afterwards, `just <something>` will work in all steps.

**Comment by springmeyer** [comment]
> How about we aim to get CI green with the existing structure (ideally this week) and then with that foundation in place we could re-organize the repo soon after while ensuring all tests keep passing (of course the gh actions workflow will need updated too)?

CI is green now 🎉 So, I volunteer to take this re-organization on. I'll put a PR up today for review, and let's aim to merge by tomorrow, latest.

**Comment by springmeyer** [comment]
First draft of an attempt to implement this at https://github.com/maplibre/maplibre-tile-spec/pull/72#issuecomment-2146612346.

The most involved change was the introduction of `test/expected`. Previously everything was in `test/fixtures/` so repointing some tests to `test/expected` required a number of changes across test files. But it was reasonably easy to do.

**Comment by springmeyer** [comment]
Will close this: #72 is merged which lands most of the directory-level organization ideas this issue proposed. One thing I missed (looking back now) is moving the spec from `spec` to `spec/v0`. If that is important to others, seems easy to do by anyone in a followup PR.

Additionally there are some good ideas above about orchestration. I propose separate issues for those ideas be created, as needed.
