### ISSUE TITLE
Get MltDecoderTest.compareTiles working

### ISSUE THREAD

**Issue by springmeyer** [maplibre/maplibre-tile-spec#51]
I noticed that the tile comparison in the decoder tests only asserts on Feature IDs and currently not more: https://github.com/maplibre/maplibre-tile-spec/blob/22a0fc8659962d313af78dab8a4c01fd5024fbe3/converter/java/src/test/java/com/mlt/decoder/MltDecoderTest.java#L90-L136.

_(There are some asserts, but they are commented)._

This needs to assert on all aspects of the MVT spec that are comparable, including:

- Layer names
- Feature properties
- Feature geometry type and coordinates

/cc @mactrem @ebrelsford @nyurik

**Comment by mactrem** [comment]
@springmeyer yes, I always have tested all information of the tile. But as I’m currently doing a larger refactoring where a lot of has changed, I step by step getting the tests to run again and adding the asserts on different aspects step by step. I hope to commit a version by today where all aspects are tested again

**Comment by springmeyer** [comment]
Asserts restored now (https://github.com/maplibre/maplibre-tile-spec/blob/1d08bd24c7661883a3b0fd2b518880dcc0fcecf6/converter/java/src/test/java/com/mlt/decoder/MltDecoderTest.java#L126-L211) after #52
